CREATE TABLE april11 (
    order_id INT,
    customer_id INT,
    restaurant_name VARCHAR(50),
    order_date DATE,
    delivery_time INT,      -- in minutes
    order_value INT,
    rating INT,             -- 1 to 5
    payment_method VARCHAR(20)  -- UPI / Cash / Card
);

INSERT INTO april11 VALUES
(101, 1, 'Dominos', '2024-01-01', 30, 250, 4, 'UPI'),
(102, 2, 'KFC', '2024-01-01', 45, 400, 5, 'Card'),
(103, 1, 'Dominos', '2024-01-03', 25, 300, 3, 'Cash'),
(104, 3, 'Burger King', '2024-01-02', 50, 350, 4, 'UPI'),
(105, 2, 'KFC', '2024-01-04', 40, 450, 5, 'UPI'),
(106, 4, 'Subway', '2024-01-02', 20, 200, 2, 'Cash'),
(107, 5, 'Dominos', '2024-01-03', 35, 280, 4, 'Card'),
(108, 3, 'Burger King', '2024-01-05', 55, 500, 5, 'UPI'),
(109, 1, 'Subway', '2024-01-06', 15, 150, 3, 'UPI'),
(110, 2, 'KFC', '2024-01-06', 60, 550, 4, 'Card'),
(111, 4, 'Dominos', '2024-01-07', 28, 260, 5, 'UPI'),
(112, 5, 'Subway', '2024-01-08', 22, 210, 3, 'Cash');

select * from april11;

---Find total revenue generated by each restaurant
select restaurant_name, sum(order_value) as revenue_generated from april11
group by restaurant_name;

---Find average delivery time per restaurant
select * from april11;

select restaurant_name , avg(delivery_time) as avg_delivery_time from april11
group by restaurant_name;

---Find number of orders per payment method
select payment_method, count(order_id) as number_orders from april11
group by payment_method;

---Find the highest order value per customer
select * from april11;

select customer_id ,max(order_value) as highest_order_value from april11
group by customer_id;

---Find customers who placed more than 2 orders
select * from april11;

select customer_id ,count(*) as order_count from april11
group by customer_id 
having count(*) > 2;

---Find the top 3 customers by total spending
select * from april11;

select top 3 customer_id ,sum(order_value) as total_spending from april11
group by customer_id 
order by sum(order_value) desc;

---Find restaurants with average rating > 4
select * from april11;

select restaurant_name , avg(rating) as average_rating from april11
group by restaurant_name 
having avg(rating) > 4;

---Find orders where delivery time is above average
select * from april11;

select * from april11 where delivery_time > (select avg(delivery_time) as avg_time from april11);

---Find most frequently used payment method
select * from april11;

select top 1 payment_method , count(*) as count_data from april11
group by payment_method 
order by count(*) desc;

---Rank restaurants based on total revenue
select * from april11;

select restaurant_name , sum(order_value) as total_revenue ,rank() over
(order by sum(order_value) desc) as rnk from april11
group by restaurant_name;

---Find customer retention (customers ordering again within 3 days)
select * from april11;

WITH orders_lag AS (
    SELECT 
        customer_id,
        order_date,
        LAG(order_date) OVER (PARTITION BY customer_id ORDER BY order_date) AS prev_order
    FROM april11
)
SELECT DISTINCT customer_id
FROM orders_lag
WHERE DATEDIFF(day, prev_order, order_date) <= 3;

---Find peak order day (highest number of orders)
select * from april11;

select top 1 order_date, count(*) as order_count from april11
group by order_date 
order by  count(*) desc;

----Categorize Orders
select order_id , customer_id , order_value, 
case when order_value > 400 then 'high value'
when order_value between 200 and 400 then 'Medium' 
else 'low'
end as order_category 
from april11;

